### ISSUE TITLE
Should close withdrawn nomination

### ISSUE THREAD

**Issue by katiechan** [Zitrax/FPCBot#6] opened 2016-01-28 23:57 UTC
Does not currently archives withdrawn nominations

**Comment by eatcha-wikimedia** [comment] 2019-05-21 13:12
Actually it archives them, see the following links:

 https://commons.wikimedia.org/w/index.php?title=Commons:Featured_picture_candidates/File:Bahram_Gur_hunting.jpg&diff=29349374&oldid=29204723 (User:Yann used withdrawn template)

https://commons.wikimedia.org/w/index.php?title=Commons:Featured_picture_candidates/candidate_list&diff=prev&oldid=29416926 (bot removed it from the candidate list)

I'm testing it on the `[FPC](https://commons.wikimedia.org/wiki/Commons:Featured_picture_candidates)`, to check if it needs a patch.


[User:Eatcha](https://commons.wikimedia.org/wiki/User:Eatcha)

**Comment by eatcha-wikimedia** [comment] 2019-05-25 11:37
Yeah, It actually didn't worked since 2013-22-september. The last image it closed as withdrawn nomination is https://commons.wikimedia.org/wiki/Commons:Featured_picture_candidates/File:Carex_muricata_-_siiltarn_Keilas.jpg see https://commons.wikimedia.org/w/index.php?title=Commons:Featured_picture_candidates/candidate_list&diff=prev&oldid=105038826

**Comment by eatcha-wikimedia** [comment] 2019-05-25 20:43
No it's not because of Wikipedia to pywikibot library conversion, confirmed by a pywikibot developer

**Closed** 2019-05-26 15:07 UTC
